version: "3.8"

services:
  fbfarm:
    build: .
    stop_signal: SIGINT
    restart: always
    volumes:
      - ./DB:/app/DB
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - default

  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379"
    networks:
      - default


networks:
  default:
    driver: bridge